### ISSUE TITLE
Finish the renaming of cf-operator → quarks-operator

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/quarks-operator#1008]
The project and repo have been renamed a while ago, so I'm surprised that a major new release (`5.0.0`) is still releasing images and helm charts under the legacy name.

I'm even more surprised that I can't find an open issue to finish the renaming; what is the plan? Keeping the old name externally is just confusing for end-users, or new contributors who are not familiar with the project history.

**Comment by manno** [comment]
Hey @jandubois thanks for opening the issue.
We decided to add new stories for the remaining renaming. We haven't done that yet and didn't consider the rename as a priority.

**Comment by manno** [comment]
The chart, binary and docker image were renamed:

* https://www.pivotaltracker.com/story/show/174254515
* https://www.pivotaltracker.com/story/show/171525034
