### ISSUE TITLE
Removing instance group does not remove QuarksStatefulSet

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/quarks-operator#1023]
**Describe the bug**
When an instance group is removed from the deployment manifest, the corresponding instance group is not removed.

**To Reproduce**
1. Deploy KubeCF.
2. Wait for it to settle.
3. Apply the following ops file†:
```yaml
- type: remove
  path: /instance_groups/name=nats
```
4. Reinstall the helm chart (as an upgrade).

† This can be accomplished with a custom `values.yaml` for the kubecf chart:
```yaml
system_domain: blah.example.com
operations:
  inline:
  - type: remove
    path: /instance_groups/name=nats
```

**Expected Behaviour**
The `nats` QuarksStatefulSet should be removed.

**Actual Behaviour**
The `nats` QuarksStatefulSet remains.

**Environment**
 - CF-Operator Version: `v5.0.0-0.gd7ac12bc`
 - KubeCF `master`

**Additional context**
Manually deleting the QuarksStatefulSet doesn't make it come back again.

It does have the correct information, so that we _should_ be able to track it:
```yaml
metadata:
  creationTimestamp: "2020-07-07T22:39:58Z"
  generation: 1
  labels:
    quarks.cloudfoundry.org/deployment-name: kubecf
    quarks.cloudfoundry.org/deployment-version: "0"
    quarks.cloudfoundry.org/instance-group-name: nats
  name: nats
  namespace: kubecf
  ownerReferences:
  - apiVersion: quarks.cloudfoundry.org/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: BOSHDeployment
    name: kubecf
    uid: 14a54471-b113-4c13-8db9-8daf74682ab9
  resourceVersion: "239622"
  selfLink: /apis/quarks.cloudfoundry.org/v1alpha1/namespaces/kubecf/quarksstatefulsets/nats
  uid: 06252470-f068-4b69-abce-926859edd686
```

Also note that removing `nats` *does* cause all the things that require it to break (because `template-render` can no longer find the link).  So the changes are being applied, but not wholly.

**Comment by rohitsakala** [comment]
Hi @mook-as,

Added the feature with this PR https://github.com/cloudfoundry-incubator/quarks-operator/pull/1039. Re-open is you still see the issue.
