### ISSUE TITLE
Passwords getting unnecessarily rotated

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/quarks-operator#1169]
**Describe the bug**

Upgrading KubeCF from 2.2.3 to 2.5.4 triggers database passwords to rotate.

**To Reproduce**

Perform the upgrade (or something similar to what KubeCF does and watch the secret value ~unnecesarily~ change).

**Expected behavior**

Passwords shouldn't be unnecessarily rotated.

**Environment**

quarks-operator version 6.1.8+0.g2821133a.

**Comment by fargozhu** [comment]
fixed by #1174

**Comment by manno** [comment]
Same as https://github.com/cloudfoundry-incubator/quarks-operator/issues/1170
