### ISSUE TITLE
dm qjobs are left undeleted

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/quarks-operator#1170]
**Describe the bug**

When upgrading from a quarks-operator that created the `dm` qjob to a quarks-operator that doesn't, leads to multiple `dm` qjobs runs + multiple `ig` qjobs runs (eventually crashing k8s nodes).

**Expected behavior**

Perhaps a Helm pre-upgrade hook could delete the old `dm` qjobs?

**Environment**

quarks-operator version 6.1.8+0.g2821133a.

**Comment by manno** [comment]
We fixed a bug with triggering quarks-secret updates manually from the deployment reconciler.

**Comment by f0rmiga** [comment]
@manno Without any reference to a commit, I cannot assert that this was indeed fixed. I highly doubt that this issue was fixed, as I'm currently working on a pre-upgrade hook to get rid of the `dm` job.

**Comment by fargozhu** [comment]
It should have been closed by merging the pull request #1179.

**Comment by f0rmiga** [comment]
Interestingly, it did not close automatically. /shrug
