### ISSUE TITLE
Bootstrap not run when not enough replicas

### ISSUE THREAD

**Issue by mook-as** [cloudfoundry-incubator/quarks-operator#1182]
**Describe the bug**
When:
 - Some instance group wants multiple replicas (e.g. `credhub`, wants 3)
 - We do an upgrade (so `INITIAL_BOOTSTRAP` is `false`)
 - The instances are crashing for some reason in the middle of the upgrade (e.g. because a dependency has other issues)
Then:
 - The number of replicas for the instance group can temporarily be lower than the maximum (e.g. maybe the `credhub-2` pod is temporarily removed, and `credhub-1` is crashing)
 - Because only `credhub-2` is the bootstrap pod, when `credhub-1` is recreated (with the new containers) migration never happens

**To Reproduce**
- Install stuff
- Pick something with multiple replicas, and then make it fail enough that some replicas are removed
    - e.g. have multiple replicas crash to backoff simultaneously, so that some of the replicas are removed temporarily
- Upgrade it (so `INITIAL_BOOTSTRAP` will be `false`)

**Expected behaviour**
Bootstrap should be run on the first instance of the upgraded pod (i.e. the first pod using the new container setup, e.g. image)

**Actual behaviour**
Bootstrap is never run, because the replica that is set to be bootstrap (`replicas - 1`) doesn't exist yet; and since that has not run, the existing replicas (`replicas - 2`, etc.) will never be ready, which means the one we need never starts.

**Environment**
 - CF-Operator Version: `6.1.15+0.g89a56300`
 - KubeCF: `2.5.6`

**Additional context**
I believe SCF handled this by actually checking for all the replicas with the same image, and assuming upgrade if there's one of them (the current one); see [code](https://github.com/cloudfoundry-incubator/configgin/blob/0.20.3/lib/job.rb#L15).

**Comment by manno** [comment]
I believe this will fix it: https://github.com/cloudfoundry-incubator/quarks-operator/pull/1237
