### ISSUE TITLE
POD draining does not work because individual containers terminate prematurely instead of waiting for the completion of all drain/preStops on all containers

### ISSUE THREAD

**Issue by univ0298** [cloudfoundry-incubator/quarks-operator#1297]
**Describe the bug**
Note: This is a follow on to https://github.com/cloudfoundry-incubator/quarks-operator/issues/1283
A concise explanation of the bug is that in quarks the containers in a pod all have individual lifecycles and will terminate as soon as their individual drain completes. Whereas BOSH ensures that all jobs on a server remaining running until the last job has finished draining, and then BOSH terminates them all together .

Some more information:
When a pod is being shutdown (for example for maintenance update), the drain mechanisms that ensure non-disruptive behavior are broken because individual jobs/containers terminate as soon as their individual drains are complete. BOSH behaves differently and many releases/components in BOSH rely on the different behavior. With BOSH, when a VM is being stopped, all jobs will stay running until every job's drain has completed and only then will the jobs be stopped.

Consider a real example:
On a Diego-cell you have rep and garden jobs. Typically the rep's drain will take a long time as it is trying to evacuate user application instances to other cells (to avoid application downtime) before eventually terminating those application instances, at which point the drain is complete. 
But for rep to do this the garden job MUST stay running on that cell (rep needs garden). But in quarks/kubeCF it does not stay running due to garden's own drain having already completed long before the rep is finished draining.

**To Reproduce**
From a kubeCF system, initiate `kubectl -n <namespace> delete pod diego-cell-0` and see in the logs that the rep ends before evacuation is complete. Or for a more complete demonstration, try having a single instance app running on the diego-cell-0 and constantly curling the app to test it, when you delete the pod. The app will immediately see failures as the rep drain failed because garden's drain finishes before rep is able to properly evacuate the app to another host.

**Expected behavior**
As in BOSH, all containers in the pod should stay running until the drain (preStop) has completed for all containers

**Environment**
 - CF-Operator Version: 7.2.1
 - Others - We are using KubeCF 2.7.12

**Additional context**
Note: This is a follow on to https://github.com/cloudfoundry-incubator/quarks-operator/issues/1283

**Comment by manno** [comment]
We currently need this only for diego?
Might be easier to fix it there. 

Otherwise we have to modify container-run to wait. (Last time we couldn't figure out how to update container-run to the latest Go version.)
container-run probably needs to know the name of the containers and how to check if they're done. There is some (TCP?) socket code in container-run already. 

* c-r is configured with a list of containers to wait for
* c-r opens a "health check" port when it starts
* when drain is done, goes into an endless loop, until all configured "health checks" are false
?

**Comment by univ0298** [comment]
Not only for Diego - it's a general issue as many Cloud Foundry components have drain to ensure graceful quiesce. But the diego cells are where the biggest problem is seen as applications end up with outages.

Not sure if I totally follow your thinking here on health checking sorry. Could you elaborate some more?

**Comment by jandubois** [comment]
So here is my idea how to implement this without touching container-run:

The drain script is already being called in a bash `PreStop` hook for each container: https://github.com/cloudfoundry-incubator/quarks-operator/blob/01b99d5/pkg/bosh/bpmconverter/container_factory.go#L622-L649

(I don't see how the code handles the absence of a drain script gracefully; maybe that needs some extra logic?)

And we also have a shared volume mounted in all containers: `/var/vcap/data`.

Once the drain script has finished successfully (or if there is no drain script for this job), the `PreStop` hook will touch a file `/var/vcap/data/drain-done/$JOB`. Afterwards it just waits:

```
while [ $(ls -1 /var/vcap/data/drain-done | wc -l) -lt $NO_OF_JOBS ]; do sleep 5; done
```

That way it it will wait until all drain scripts have finished, or until the `graceTerminationPeriod` has expired, whichever comes first.

I don't know if there is a way to pass the number of jobs in the instance group to `bpmProcessContainer` to set `$NO_OF_JOBS`. If there isn't, then maybe each init container for each job can touch a file in a different directory, and we can check something like:

```
while [ $(ls -1 /var/vcap/data/drain-done | wc -l) -lt $(ls -1 /var/vcap/data/drain-waitfor | wc -l) ]; do
    sleep 5
done
```

I'm not sure what the appropriate argument for `sleep` should be. I first had it at `1`, but that may be too short; `5` feels like a reasonable compromise, but I just picked it out of thin air...

@manno What do you think; should this work and be easy enough to implement?

**Comment by univ0298** [comment]
This makes sense to me @jandubois .. 
I would guess the sleep/wait should be about 5-10 seconds. Drains typically have 5-10 second waits in their own loops. And in the timeline of a pod shutdown I think 5 or even 10 seconds is not a big deal.

**Comment by univ0298** [comment]
Any news on this?

**Comment by manno** [comment]
So in addition TerminationGracePeriod needs to be really high, since PreStop doesn't stop graceful termination: 
> The Pod's termination grace period countdown begins before the PreStop hook is executed, so regardless of the outcome of the handler, the container will eventually terminate within the Pod's termination grace period. No parameters are passed to the handler.
https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks

* Looking at the issues in k8s [#94435](https://github.com/kubernetes/kubernetes/issues/94435) I'm not sure how  well long durations (>10min) are supported.
* I remember we had code to sleep/wait for files in quarks-jobs and it was not robust, we used inotify instead (fsnotify). However  EmptyDir volumes support multiple writes and can be on a tmpfs.
* The sleep duration must be smaller, than the grace period. However it seems like drain jobs can control this themselves.
* Looks like the bpm container factory can know the number of jobs up front.

I'll try an implementation.

**Comment by manno** [comment]
This is what I'm currently trying: https://github.com/cloudfoundry-incubator/quarks-operator/pull/1302/commits/83f6b33c45f6d02ecf235883ccc318f2b79e0353

**Comment by univ0298** [comment]
As commented in https://github.com/cloudfoundry-incubator/quarks-operator/commit/83f6b33c45f6d02ecf235883ccc318f2b79e0353 , this doesn't work correctly. Please could you re-open the issue?

**Comment by univ0298** [comment]
@manno as commented in https://github.com/cloudfoundry-incubator/quarks-operator/pull/1302 this doesn't work correctly. Please could you re-open the issue?
