### ISSUE TITLE
upgrade of kubeCF from version 2.7.12 to 2.7.13 fails when using "helm upgrade"

### ISSUE THREAD

**Issue by deepaksharma009** [cloudfoundry-incubator/quarks-operator#1311]
**Describe the bug**
"cf-operator-pre-upgrade-hook" is failing (during helm upgrade of kubeCF) with image pull back error while pulling one image from the private image registry of ours though I have provided the correct credentials in values.yaml already for private regsitry access.

**To Reproduce**
Install kubeCF-v2.7.12 and then run helm upgrade command to upgrade to kubeCF-v2.7.13, during upgrade the image pull down from the private registry fails. The error happens during pulling down the kubcf-kubectl image says that invalid credentials for accessing the private registry in order to download the image. Though the same credentials and everythig is same during the install of kubeCF-v2.7.13 independently (during "helm install" of kuneCF-v2.7.13). 

**Expected behavior**
I should be able to upgrade the kubeCF from version 2.7.12 to 2.7.13 using helm upgrade command

**Environment**
 - CF-Operator Version: 7.2.1+0.gaeb6ef3
 - kubeCF version 2.7.13
 
**Additional context**
I have done installation of kubecf version 2.7.12 as well as 2.7.13 separately and successfully and it did worked fine in both cases. but simply upgrade from kubeCF-v2.7.12 to kubeCF-v2.7.13 fails (using "helm upgrade".

**Comment by jandubois** [comment]
Yes, this is a bug. The pull-secret is only defined for the operator service account, but not for the hook service accounts.

You need to copy the logic from `templates/service-account-pull-secret.yaml` into the `templates/service-account-hooks.yaml` (and adjust the names accordingly, of course).

If you have the skills, please file a pull request after testing the change!
