### ISSUE TITLE
Overriding a variable value after the quarks-operator generated it doesn't work

### ISSUE THREAD

**Issue by f0rmiga** [cloudfoundry-incubator/quarks-operator#925]
**Describe the bug**

As part of https://github.com/cloudfoundry-incubator/kubecf/pull/814, specifying values for variables is possible during the initial deployment. I asserted that setting `credentials.cf_admin_password` works as expected, as well as adding an implicit variable using the `variables` key presented on that PR.

After the initial deployment finished, I then moved to set `credentials.router_ssl.certificate` and `credentials.router_ssl.private_key`. My hope was that the quarks-operator would pick those changes and use the new values, restarting the `router` instance group. The `router` did **not** get restarted.

When I check for the secrets on k8s, I see:

```
NAME              TYPE     DATA   AGE
cred-router-ssl   Opaque   3      6m50s
```
```
NAME             TYPE     DATA   AGE
var-router-ssl   Opaque   4      29m
```

The `cred-router-ssl` being the one created after the fact with the expected values to be used instead of the `var-router-ssl`.

If I apply the following operations and delete the `var-router-*` related secrets, the quarks-operator picks the changes and restarts `router` with the correct values:

```yaml
- type: remove
  path: /variables/name=router_ca
- type: remove
  path: /variables/name=router_ssl
```

**To Reproduce**

It's part of the description.

**Expected behavior**

The new values should just be picked and `router` should be restarted.

**Comment by manno** [comment]
We believe this is fixed

**Comment by jandubois** [comment]
@manno I think it would be nice to include a link to the PR or commit that fixed an issue, instead of just closing it. If there ever is doubt in the future about the fix, it makes it easy to locate the change and read through the tests created for this issue.

The same way it would have been nice if the fixing PR included a link back to this issue, to provide additional context if somebody wants to understand the reason for the change at a later time.

**Comment by univ0298** [comment]
@jandubois @manno yes Jan's comment above was correct, since I am right now looking for the code that does this and wishing there was a link here !
