### ISSUE TITLE
operator should be able to delete / override old CSR

### ISSUE THREAD

**Issue by prabalsharma** [cloudfoundry-incubator/quarks-operator#952]
**Describe the bug**
To avoid issues like https://github.com/cloudfoundry-incubator/kubecf/issues/877, it will be nice if operator could delete / override old CSR. According to @viovanov, operator has such feature but maybe its not functioning correctly.

**To Reproduce**
Deploy kubecf with eirini enabled on a cluster with old bits-CSR

**Expected behavior**
 https://github.com/cloudfoundry-incubator/kubecf/issues/877,

**Environment**
cf-operator-4.5.6+0.gffc6f942 

**Additional context**

**Comment by rohitsakala** [comment]
Hi @prabalsharma , Thank you for reporting the issue. The issue should be resolved with #962 . The feature was already implemented in cf-operator, but the right permissions were missing for the cf-operator role.
