### ISSUE TITLE
Add support for resource limits and requests

### ISSUE THREAD

**Issue by jandubois** [cloudfoundry-incubator/quarks-operator#973]
I wanted to define a memory limit on the log-cache instance group because it has a known memory leak when running more than one instance. It looks like quarks-operator has no support for this.

I expected that AgentSettings would include `Limits` and `Requests` fields, or something similar, but didn't find anything.

**Comment by viovanov** [comment]
The table here is wrong: https://github.com/cloudfoundry-incubator/quarks-operator/blob/2ba6e835cad187b9299892142dffa908a1debb10/docs/from_bosh_to_kube.md#resources

It is implemented for memory.
AgentSettings exist per Instance Group, so they usually apply to a Pod or StatefulSet.
Limits are set per container (equivalent of BPM processes).

**Comment by jandubois** [comment]
> Limits are set per container (equivalent of BPM processes).

Thanks! I've been able to set a limit with:

```
  - type: replace
    path: /instance_groups/name=log-cache/jobs/name=log-cache/properties/quarks?/bpm/processes/name=log-cache/limits/memory
    value: 2G
```
