### ISSUE TITLE
Ig secret having unrendered variables

### ISSUE THREAD

**Issue by rohitsakala** [cloudfoundry-incubator/quarks-operator#987]
Issue mentioned in KubeCF repo - https://github.com/cloudfoundry-incubator/kubecf/issues/973

**Comment by jandubois** [comment]
Isn't this a duplicate of #750?

**Comment by rohitsakala** [comment]
> Isn't this a duplicate of #750?

No, this issue is related to ig secrets having explicit variables not being rendered as Mark has pointed out.

**Comment by rohitsakala** [comment]
Hi @mook-as ,

This issue should be fixed with these PR's - https://github.com/cloudfoundry-incubator/quarks-operator/pull/1013. I checked on latest cf-operator and kubecf v2.2.0.
